// Public Counting assets only. The fake preview and private fixture data are not build inputs.
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { basename } from "node:path";
import { createHash } from "node:crypto";
import { build } from "esbuild";

const here = path => fileURLToPath(new URL(path, import.meta.url));
export const MODULE = here("../../../packages/scope/src/counting-assets.ts");
export const OUTPUT = here("../browser-build/");
const TYPES = { "index.html": "text/html; charset=utf-8", "counting.js": "text/javascript; charset=utf-8", "counting.css": "text/css; charset=utf-8" };
const digest = text => createHash("sha256").update(text, "utf8").digest("hex");

export async function countingFiles() {
  const bundled = await build({ entryPoints: [here("../browser/main.ts")], bundle: true, format: "esm", platform: "browser", target: "es2022", minify: true, legalComments: "none", write: false, logLevel: "silent", outfile: here("../browser-build/counting.js") });
  const outputs = Object.fromEntries(bundled.outputFiles.map(file => [basename(file.path), file.text]));
  if (Object.keys(outputs).sort().join(",") !== "counting.css,counting.js") throw new Error("Counting build has unexpected assets.");
  const source = await readFile(here("../browser/index.html"), "utf8");
  const script = '<script type="module" src="./main.ts"></script>';
  if (source.split(script).length !== 2 || !source.includes("</head>")) throw new Error("Counting entry HTML is not the owned source.");
  const html = source.replace(script, '<script type="module" src="./counting.js"></script>').replace("</head>", '<link rel="stylesheet" href="./counting.css"></head>');
  const files = { "index.html": html, "counting.js": outputs["counting.js"], "counting.css": outputs["counting.css"] };
  for (const text of Object.values(files)) if (typeof text !== "string" || Buffer.byteLength(text, "utf8") > 2 * 1024 * 1024) throw new Error("Counting asset is missing or too large.");
  return files;
}
export async function countingAssets() {
  const files = await countingFiles();
  return ["// GENERATED by examples/counting/scripts/assets.mjs. Do not edit.", "// Public production entry only; no fake preview, keys, sessions or recorded fixture data.", ...Object.entries(files).map(([name, body]) => `// sha256 ${name} ${digest(body)}`), `export const COUNTING_ASSETS = ${JSON.stringify(Object.fromEntries(Object.entries(files).map(([name, body]) => [name, { type: TYPES[name], body }]))) } as const;`, ""].join("\n");
}
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const files = await countingFiles();
  // Use exactly the same build for the disk files and the Worker module.
  const module = ["// GENERATED by examples/counting/scripts/assets.mjs. Do not edit.", "// Public production entry only; no fake preview, keys, sessions or recorded fixture data.", ...Object.entries(files).map(([name, body]) => `// sha256 ${name} ${digest(body)}`), `export const COUNTING_ASSETS = ${JSON.stringify(Object.fromEntries(Object.entries(files).map(([name, body]) => [name, { type: TYPES[name], body }]))) } as const;`, ""].join("\n");
  await mkdir(OUTPUT, { recursive: true });
  for (const [name, body] of Object.entries(files)) await writeFile(here(`../browser-build/${name}`), body);
  await writeFile(MODULE, module);
  console.log("Wrote the three public Counting assets and Worker module.");
}
