// The page's build: one bundle by esbuild, and the module of the scope package that the scope Worker serves at `/page/`.
//
//   node scripts/assets.mjs           writes dist/index.html, dist/page.js and ../scope/src/page-assets.ts
//
// `pageAssets()` gives the text of that module without writing anything; the page's test `assets.test.ts` compares it with the
// committed file, so the Worker never serves a page older than its source.
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
import { build } from "esbuild";

const here = (path) => fileURLToPath(new URL(path, import.meta.url));
export const MODULE = here("../../scope/src/page-assets.ts");

/** The page's two files: the HTML and the bundled, minified script. */
export async function pageFiles() {
  const bundled = await build({
    entryPoints: [here("../src/main.ts")], bundle: true, format: "esm", platform: "browser", target: "es2022", minify: true, legalComments: "none", write: false, logLevel: "silent",
  });
  return { html: await readFile(here("../src/index.html"), "utf8"), js: bundled.outputFiles[0].text };
}

/** The scope package's module that holds the two files, as text. */
export async function pageAssets() {
  const { html, js } = await pageFiles();
  const digest = (text) => createHash("sha256").update(text, "utf8").digest("hex");
  return [
    "// GENERATED by packages/page/scripts/assets.mjs (npm run build --workspace @generalbusiness/artroom-page). Do not edit.",
    "// The page that the scope Worker serves at /page/ (`page.ts`): its HTML and its one script, bundled from packages/page/src.",
    `// sha256 of index.html ${digest(html)}`,
    `// sha256 of page.js ${digest(js)}`,
    `export const PAGE_HTML: string = ${JSON.stringify(html)};`,
    `export const PAGE_JS: string = ${JSON.stringify(js)};`,
    "",
  ].join("\n");
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const { html, js } = await pageFiles();
  await mkdir(here("../dist"), { recursive: true });
  await writeFile(here("../dist/index.html"), html);
  await writeFile(here("../dist/page.js"), js);
  await writeFile(MODULE, await pageAssets());
  console.log(`page.js ${js.length} bytes; wrote dist/ and ${MODULE}`);
}
