/** Manifest-list successors; generated by scripts/pin.mjs. */
export const MANIFEST_DIGESTS = { change: "sha256:cad70aa528e3fa95a10080d896656e181ccf614e06a3e23080855834cb26edea", demo: "sha256:012432b5ec1a77389bafa0a53c214d52bfb95c39e704b0221f46b28a876de486" } as const;
