/** Manifest-list successors; generated by scripts/pin.mjs. */
export const MANIFEST_DIGESTS = { change: "sha256:108086bf0795547e14157b14652eb42dbc06c60b8a051c680412b670b91ab19f", demo: "sha256:65e0189aac98313f873bee35253f3d2e1333ecbb13e066b0b808ce01b203cad4" } as const;
