/** Manifest-list successors; generated by scripts/pin.mjs. */
export const MANIFEST_DIGESTS = { change: "sha256:797e0b60f6b985f73327264f0f64aa67c697b2c9e8273dc01318faa47590712b", demo: "sha256:e1eefc0aec645841e7f65fd0a19aa628937e9d093988ec485c8b089e7d2bb6c6" } as const;
