/**
 * The UI's only import site for the lane 0 contract
 * (@generalbusiness/artroom-contract, commit 845c7fd7, under review).
 *
 * Everything else in the UI imports contract types from here, so a change in
 * the contract is absorbed in this folder (src/room) and nowhere else.
 */

export type {
  ActDeclaration,
  ActId,
  ActsCatalogue,
  AbortAttempt,
  AnyEnvelope,
  ArtroomError,
  AttentionItem,
  Authority,
  Binding,
  Carried,
  Catalogue,
  CatalogueAt,
  CarryReason,
  Check,
  CheckerConfig,
  Claim,
  Cursor,
  Decision,
  DeclaredEnvelope,
  DeclaredField,
  DeclaredRecord,
  DeclaredTarget,
  Digest,
  EntrySummary,
  Evidence,
  Flag,
  Generation,
  Glob,
  HttpRoom,
  Json,
  KindName,
  Lane,
  FailReason,
  LandOp,
  LogEntry,
  LogPage,
  Member,
  MemberId,
  Note,
  NoteAnchor,
  NotCarried,
  Obligation,
  OpId,
  Overlap,
  Page,
  PathChange,
  PolicyActor,
  PolicyDocument,
  PolicyLane,
  PolicyProposal,
  PolicyRoom,
  PolicyVersion,
  PreviewOp,
  Principal,
  Proposal,
  ProposalAt,
  ProposalRef,
  PublicationSlot,
  ReadBack,
  RecordMeaning,
  RetryReason,
  Reason,
  Refusal,
  RepoPath,
  Result,
  RefuseRule,
  RequireRule,
  Review,
  ReviewedHere,
  ReviewerSpec,
  Role,
  RoomId,
  Roster,
  Rule,
  RuleId,
  RuleInput,
  Seq,
  Sha,
  Step,
  Subscription,
  SystemEvent,
  TargetShape,
  Timestamp,
  Update,
  Verdict,
} from "@generalbusiness/artroom-contract";

export { envelopeOf, isCarried, isHeld, isRefusal, holdsSlot, isTerminal } from "@generalbusiness/artroom-contract";
