import { chromium } from '/Users/hughpyle/.npm/_npx/e41f203b7505f1fb/node_modules/playwright/index.mjs';
import { writeFile } from 'node:fs/promises';
const dir = '/Users/hughpyle/play/artroom-worktrees/usability-review/plans/027-artroom-usability';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1024,height:1000}});
page.setDefaultTimeout(5000);
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(`file://${dir}/preview-qa.html`,{waitUntil:"domcontentloaded",timeout:30000});
const frame=page.frameLocator('iframe');
await frame.locator('#artroom-design-preview .ar-app').first().waitFor();
const results=[];
const current=()=>frame.locator('.ar-app').first();
async function check(screen,device,sample='populated',theme='light'){
  await page.emulateMedia({colorScheme:theme});
  await frame.locator('#ar-device').selectOption(device);
  await frame.locator('#ar-screen').selectOption(screen);
  await frame.locator('#ar-state').selectOption(sample);
  const measurement=await frame.locator('#artroom-design-preview').evaluate(root=>{
    const app=root.querySelector('.ar-app');
    const duplicates=[...root.querySelectorAll('[id]')].map(e=>e.id).filter((id,i,all)=>all.indexOf(id)!==i);
    const bounds=app.getBoundingClientRect();
    const clipped=[...app.querySelectorAll('button,input,select,textarea,h1,h2,p,article,nav')].filter(e=>e.getBoundingClientRect().width&&e.getBoundingClientRect().right>bounds.right+1).map(e=>e.textContent.slice(0,70));
    return {width:Math.round(bounds.width),scrollWidth:app.scrollWidth,duplicates,clipped};
  });
  if(measurement.duplicates.length||measurement.clipped.length||measurement.scrollWidth>measurement.width+1)throw new Error(`${screen}/${device}: ${JSON.stringify(measurement)}`);
  results.push({screen,device,sample,theme,...measurement});
}
for(const device of ['desktop','390','320'])for(const screen of ['issues','changes','create','rules'])await check(screen,device);
for(const device of ['desktop','390','320'])for(const sample of ['review','path','pending','published','empty'])await check(sample==='empty'?'issues':'detail',device,sample);
await check('issues','desktop');
await current().getByRole('searchbox').fill('first edit');
if(await current().locator('.ar-item').count()!==1)throw new Error('Search did not filter');
await current().getByRole('searchbox').fill('no-match');
await current().getByRole('button',{name:'Clear filters'}).click();
if(await current().locator('.ar-item').count()!==3)throw new Error('Clear filters failed');
await check('issues','320','empty');
await current().getByRole('button',{name:'Create issue',exact:true}).first().click();
await current().getByLabel('Title',{exact:true}).fill('Keep the first action obvious');
await current().getByRole('button',{name:'Create issue',exact:true}).click();
await current().getByRole('button',{name:'Keep the first action obvious'}).waitFor();
await check('create','320');
await current().getByLabel('Room name',{exact:true}).fill('Studio notes');
if(await current().getByLabel('Room address',{exact:true}).inputValue()!=='studio-notes')throw new Error('Slug generation failed');
await current().getByRole('button',{name:'Create room',exact:true}).click();
await current().getByRole('heading',{name:'Studio notes',exact:true}).waitFor();
await current().getByRole('heading',{name:'Start with one thing to do'}).waitFor();
await check('detail','desktop','review');
await current().getByRole('button',{name:'Files · 1'}).click();
await current().getByRole('button',{name:'Preview this version',exact:true}).first().click();
await current().getByText('Proposed version 5 · Unpublished · Isolated preview',{exact:true}).waitFor();
await check('detail','320','review');
await current().getByRole('button',{name:'Review change',exact:true}).click();
await current().getByRole('button',{name:'Submit review',exact:true}).click();
await current().getByRole('button',{name:'Publish change',exact:true}).click();
await current().getByRole('heading',{name:'Published',exact:true}).waitFor();
await check('detail','320','path');
await current().getByRole('button',{name:'Fix path'}).click();
await current().getByLabel('Page content',{exact:true}).fill('# Introduction\nWelcome.');
await current().getByRole('button',{name:'Propose change'}).click();
await current().getByText('Design sample: a new proposal was saved locally. It has not been published.').waitFor();
await check('rules','320');
await current().getByRole('button',{name:'Review rule changes'}).click();
await current().getByRole('button',{name:'Apply rules'}).click();
await current().getByText('Design sample: rules were applied. No real room settings changed.').waitFor();
await check('issues','desktop');
await page.screenshot({path:`${dir}/preview-desktop.png`,fullPage:true});
await check('detail','320','path');
await page.screenshot({path:`${dir}/preview-mobile-320.png`,fullPage:true});
await check('issues','390','populated','dark');
await page.screenshot({path:`${dir}/preview-mobile-390-dark.png`,fullPage:true});
await page.setViewportSize({width:320,height:1000});
await check('issues','desktop','populated','light');
await page.screenshot({path:`${dir}/preview-host-320.png`,fullPage:true});
await frame.getByRole('button',{name:'Next variant'}).click();
const sidebar=frame.locator('.ar-app').nth(1);
await sidebar.getByRole('button',{name:'Changes',exact:true}).click();
if(errors.length)throw new Error(`Browser errors: ${errors.join('; ')}`);
await writeFile(`${dir}/preview-qa-results.json`,JSON.stringify({browser:'Existing cached Playwright 1.63.0, bundled Chromium',errors,results,interactions:['search','clear filters','create issue','room name/address','create room','files','proposal preview','approve version','publish sample','fix path','review/apply rules','sidebar navigation']},null,2));
console.log(JSON.stringify({checks:results.length,errors,interactions:'passed'}));
await browser.close();
